# Ausblick

## Andere Datenformate

Bei aller Relevanz für Bibliotheken mit PICA-Systemen ist PICA nicht das einzige und nicht das wichtigste bibliothekarische Datenformat. Vor allem für den Austausch zwischen verschiedenen Bibliothekssystemen ist noch immer das über 50 Jahre alte **[MARC-Format](http://format.gbv.de/marc)** das Mittel der Wahl. Für die Verarbeitung von MARC-Daten gibt es mit [Processing MARC 21 with open source tools](https://jorol.github.io/processing-marc/#/) ein ähnliches Handbuch wie dieses.

Die Ablösung von PICA und MARC durch modernere Datenformate wird schon seit Jahrzehnten diskutiert. Eine mögliche Alternative ist [BIBFRAME](https://www.loc.gov/bibframe/) auf Basis von RDF. Daneben gibt es viele weitere Formate für bibliographische und andere Arten von Daten. Die Webseite <https://format.gbv.de/> gibt einen allgemeinen Überblick fast aller Formate die im Bibliotheksbereich relevant sein könnten.

Hilfreich für die Arbeit mit verschiedenen Datenformaten ist zumindest ein Grundverständnis allgemeiner Datenstrukturierungssprachen wie JSON, XML, RDF und CSV. 

## Allgemeines und Weiterführendes zur Datenverarbeitung

::: {.callout-important appearance="simple"}
Dieser Abschnitt muss erst noch geschrieben werden!
:::

* Wohin mit weiteren Fragen?

* Was und wie gibt es noch zu lernen (Library Carpentry etc.)?

